# Generated by Django 4.0.6 on 2023-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('locate', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField()),
                ('toggle_notifcation', models.BooleanField(default=False)),
            ],
        ),
    ]
