# Generated by Django 4.0.6 on 2023-05-30 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(default='người dùng không chia sẻ thông tin')),
                ('role', models.CharField(choices=[('S', 'Học sinh'), ('T', 'Giáo viên'), ('A', 'admin')], default='S', max_length=1)),
                ('rank', models.CharField(choices=[('A', 'Vàng'), ('B', 'Bạc'), ('C', 'Đồng'), ('U', 'Chưa xếp hạng')], default='U', max_length=1)),
                ('NumberOfPosts', models.IntegerField(default=0)),
                ('NumberOfGoodPosts', models.IntegerField(default=0, help_text='tăng giá trị nếu bài viết của người dùng là tự viết')),
                ('points', models.IntegerField(default=0, help_text='Điểm | dựa trên số bài viết đã đăng')),
                ('chatGPTLimit', models.IntegerField(default=0, help_text='Giới hạn sử dụng ChatGPT API')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
